FROM python:3.11-slim-buster

ENV TZ   Asia/Tokyo
ENV LANG ja_JP.UTF-8
ENV FLIT_ROOT_INSTALL 1

# Copy local scripts into container.
COPY ./. /root/app/
WORKDIR /root/app

RUN set -x \
  && echo "Asia/Tokyo" > /etc/timezone \
  && apt-get update \
  && apt-get -y install \
  git \
  make \
  && pip install \
  flit \
  && cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# Install libraries
RUN set -x \
  && flit install --deps production

# Install dbt module
RUN git clone https://github.com/dbt-labs/dbt-utils.git -b 1.1.1 /root/deps/dbt-utils

ENTRYPOINT [ "python", "-m" ]
